#ifndef KOSSHI_TERRAIN_DEFINITIONS_INCLUDED
#define KOSSHI_TERRAIN_DEFINITIONS_INCLUDED 1

#define TERRAIN_SIZE_X 128*4
#define TERRAIN_SIZE_Y 256
#define TERRAIN_SIZE_Z 128*4
#define CHUNK_ROOT 64

#endif
