'use strict';
console.log('Generating resource file...');
const fs = require('fs');
const cs = new (require('./commentstripper.js'))();

var shaderfile = fs.readFileSync('src/shader.glsl', 'utf8');

// var imagefile = new Uint8Array(fs.readFileSync('../res/gee.png'));

shaderfile = cs.compile( shaderfile ).replace(/(\r\n|\n|\r)/gm, '\\n');

var vert = shaderfile.split('<vertshader>')[1];
var frag = shaderfile.split('<fragshader>')[1];

// var imgarray = '';
// for (var i = 0; i < imagefile.length; i++) {
// 	imgarray += imagefile[i] + ',';
// }

var out = `//this file is generated by res.js
const char* vertex_shader = "${vert}";
const char* fragment_shader = "${frag}";
`;

fs.writeFileSync( 'build/res.h', out );
console.log('Resource file created!');


