#ifndef KOSSHI_TERRAIN_DEFINITIONS_INCLUDED
#define KOSSHI_TERRAIN_DEFINITIONS_INCLUDED 1

#define TERRAIN_SIZE_X 1024
#define TERRAIN_SIZE_Y 512
#define TERRAIN_SIZE_Z 1024
#define CHUNK_ROOT 128

#endif